### ISSUE TITLE
Question about unused tokens

### ISSUE THREAD

**Issue by lancorrect** [zjunlp/DART#10]
Hi,

It's so kind that you release your codes. After reading the codes, I have a question about unused token. 

According to your paper, DART maps template and label as *{h<sub>1</sub>, ..., h<sub>m</sub>, ..., h<sub>m+n</sub>}* , where *h<sub>i</sub>* are the trainable parameters, and they are replaced with unused tokens(e.g., [unused1] or special tokens in vocabulary). In my opinion, they will be replaced with special tokens in high probability, because it's difficult to distinguish which token were not used during training.

However, in your codes, they are replaced with last few tokens in vocabulary. So I'd like to know how you ensure that the last few tokens in vocabulary were not used? Does it mean that I can pick tokens randomly from vocabulary to replace *h<sub>i</sub>* ?

**Comment by Riroaki** [comment]
Yes and it depends on the vocabulary. In bert model the last tokens are reserved for unused tokens and marked as `[unusedxx]`s and in roberta models things are different; we still use the last tokens and make sure they didn't show up in normal training texts.

**Comment by lancorrect** [comment]
Thanks for your reply!

As you said, things are different in roberta model and you make sure the last few tokens in vocabulary didn't show up in normal training text. 

However, it seems that you didn't implement what you said in current codes, so I'm still wondering how you ensure that they were not used?

**Comment by Riroaki** [comment]
This is an interesting question and it trace back to the way LMs build their vocabularies. Modern LMs use subwords tokenization methods: [WordPiece](https://arxiv.org/pdf/1609.08144v2.pdf) used by BERT / DistilBERT, [Unigram](https://arxiv.org/pdf/1804.10959.pdf) used by XLNet / ALBERT, and [Byte-Pair Encoding](https://arxiv.org/pdf/1508.07909.pdf) used by GPT-2 / RoBERTa models.

And to our knowledge the indexing part of these methods (i.e., to convert tokens to numeric ids), though hardly documented in related libs, ought to arrange the vocabulary order in a way that more frequent (or simpler) tokens have small indices and the less frequent ones (or more complicated ones) are placed at positions with larger indices. *Note: this is rather an observation rule and not explicitly stated in the huggingface docs.* Take the ALBERT:
```python
>>> from transformers import AutoTokenizer
>>> tk=AutoTokenizer.from_pretrained('albert-xxlarge-v2')
>>> tk.convert_ids_to_tokens(range(30))
['<pad>', '<unk>', '[CLS]', '[SEP]', '[MASK]', '(', ')', '"', '-', '.', '–', '£', '€', '▁', '▁the', ',', '▁of', '▁and', 's', '▁in', '▁to', '▁a', "'", '▁was', '▁he', '▁is', '▁for', '▁on', '▁as', '▁with']
>>> tk.convert_ids_to_tokens(range(29970, 30000))
['▁dorsum', '▁wreak', '▁$250,000', '▁emanate', '▁jaffa', '▁ghz', '▁hawkeye', '▁incremental', 'wound', '2,100', '3,300', 'phosphorylation', 'sufficiency', '▁grosvenor', '▁whirling', 'auvergne', '▁alkaline', '▁virtuoso', '▁predation', '▁saviour', '▁archivist', '▁obverse', 'error', '▁tyrion', '▁addictive', '▁veneto', '▁colloquial', 'agog', '▁deficiencies', '▁eloquent']
```

With this observation, we use the tokens with largest indices in the vocabulary as prompt tokens as an acceptable substitution for the `[unused]` tokens in ALBERT for a simple reason that they are *less* likely to appear in the sentences.
