### ISSUE TITLE
Questions about symbols

### ISSUE THREAD

**Issue by wjczf123** [zjunlp/DART#12]
Hi, i have two questions about symbols in this paper.

1. Eq. (4) shows that h_i (0<=i <=j) are trainable parameters. Thus, j is the number of trainable embedding in template. 
However, Eq. (6) shows that m is the number of trainable embedding in template. 
From Eq. (4) and template, we can see that j is the length of template and m is the length of sentence after being filled.
Thus, what is the number of trainable embedding? I think it's j.

2.  To avoid optimizing any external parameters, {h_1,...,h_m,..,h_{m+n}} is replaced with unused tokens .... What does n mean? Does it denote the number of class?

Thanks.

**Comment by Riroaki** [comment]
> 

In our paper, there has been confusion between the symbols 'j' and 'm', which actually both represent the length of template tokens. Apart from these tokens, the words corresponding to the labels (aka verbalizers) are also trainable. Therefore, the total trainable embeddings consist of both the template and label tokens' embeddings and the `n` in your second question stands for the number of verbalizers (classes).
 Thanks for pointing it out:)

**Comment by wjczf123** [comment]
Thanks.
