### ISSUE TITLE
Multi-token verbalizers

### ISSUE THREAD

**Issue by rkromann** [zjunlp/DART#2]
The current implementation requires all verbalizers to be single tokens, i.e. the word must be part of the vocabulary of the model being used. This is a significant obstacle for practical applications. I noticed there is a flag called force_single_token in get_verbalization_ids, somehow suggesting that verbalizers with more than one token should be an option. I have tried to modify this, but then I get some other errors further downstream, and I must my Pytorch skills are not quite up to the task of making the necessary modifications to the code. Any hints about how to go around this would be much appreciated.

**Comment by Riroaki** [comment]
Hi rkromann, thanks for your attention!
If you want to use a multi-token verbalizer, it is necessary to modify the codes in `pvps.py` and `encoder.py`, and also change the inference logic.
Not quite sure about this, but you may refer to some whole-word-masking training & testing sample codes like this: https://github.com/Vincent131499/Language_Understanding_based_BERT
