### ISSUE TITLE
Event extraction.

### ISSUE THREAD

**Issue by ChillingDream** [zjunlp/DART#3]
Hi, I notice that you report the few-shot results on ACE-2005 and I'm very interested in your implementation. Do you have any plan to share the code for event extraction? It would be very helpful.

**Comment by zxlzr** [comment]
Hi, thank you for your attention. We implement our model for event detection (only event argument extraction) as a classification task similar to the GLUE. We use manual prompt for each event type to classify the event argument role. Recently, the code is not available. We are  using the model in a IE toolkit for a business project.
