### ISSUE TITLE
where to find the data

### ISSUE THREAD

**Issue by zhaohan-xi** [zjunlp/DART#5]
Hi Dear Author,

When trying to run the inference.py by directly running `python inference.py`, it gives me the following error:
 
`Traceback (most recent call last):
  File "/data/co_project/DART/inference.py", line 53, in <module>
    train_data = load_examples(task_name, data_dir, TRAIN_SET, num_examples=-1)
  File "/data/co_project/DART/data_utils/processors.py", line 882, in load_examples
    examples = processor.get_train_examples(data_dir)
  File "/data/co_project/DART/data_utils/processors.py", line 700, in get_train_examples
    return self._create_examples(os.path.join(data_dir, "train.csv"), "train")
  File "/data/co_project/DART/data_utils/processors.py", line 722, in _create_examples
    with open(path, encoding='utf8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/k-shot/mr/16-13/train.csv'`

It looks like the data is not pre-downloaded. Can I ask where to download those data and how can I put them into the correct place? Thanks!

**Comment by Riroaki** [comment]
Hi, thanks for your attention!
In our project, the data preparation part follows the LM-BFF few-shot data generation here: https://github.com/princeton-nlp/LM-BFF

**Comment by Riroaki** [comment]
And after the generation process, each task's few-shot dataset should be placed at `data/k-shot/{task_name}/` directory.
Hope everything works well then, and feel free to ask more questions if any:)

**Comment by zhaohan-xi** [comment]
got it, thanks!
