### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`

### ISSUE THREAD

**Issue by rahulkishen18** [zjunlp/DART#9]
Hello!

I forked your Repo on an AWS g4dn machine and tried to train it using model - roberta-large for the SST2 classification task. It gave me a CUDA error. I tried reducing the batch size from 8-4 as well and it still didn't work. Any suggestions on how to run it ?

**Comment by Riroaki** [comment]
Hi, could you list the detailed information, like torch & cuda version and device information here?
BTW, it might help if you try run on CPU first to identify the problem; would you like to test it by setting `use_gpu` to `no` in your config file?

**Comment by humoxian** [comment]
> Hello!
> 
> I forked your Repo on an AWS g4dn machine and tried to train it using model - roberta-large for the SST2 classification task. It gave me a CUDA error. I tried reducing the batch size from 8-4 as well and it still didn't work. Any suggestions on how to run it ?

Hello , I met the same problem when I used the roberta model.  By the way, it would not raise this error when use bert model. So how did you solve this problem? Thanks very much!

**Comment by Riroaki** [comment]
Would you provide more details, like the traceback information? BTW for the error you might refer to this link:https://stackoverflow.com/questions/61473330/cuda-error-cublas-status-alloc-failed-when-calling-cublascreatehandle

It seems the error is about model's output dimension (and for bert and roberta the dimensions might be different). As I mentioned you can debug using `CUDA_LAUNCH_BLOCKING=1` or set `use_gpu` as `no` in the config to debug on cpu, which helps you in locating the issue.

**Comment by humoxian** [comment]
> Would you provide more details, like the traceback information? BTW for the error you might refer to this link:https://stackoverflow.com/questions/61473330/cuda-error-cublas-status-alloc-failed-when-calling-cublascreatehandle
> 
> It seems the error is about model's output dimension (and for bert and roberta the dimensions might be different). As I mentioned you can debug using `CUDA_LAUNCH_BLOCKING=1` or set `use_gpu` as `no` in the config to debug on cpu, which helps you in locating the issue.

Well , this is the traceback information:
![2023-05-24 15-44-14屏幕截图](https://github.com/zjunlp/DART/assets/71422364/f093b4f6-ab93-4275-8eec-722fa826c97b)

**Comment by Riroaki** [comment]
> > Would you provide more details, like the traceback information? BTW for the error you might refer to this link:https://stackoverflow.com/questions/61473330/cuda-error-cublas-status-alloc-failed-when-calling-cublascreatehandle
> > It seems the error is about model's output dimension (and for bert and roberta the dimensions might be different). As I mentioned you can debug using `CUDA_LAUNCH_BLOCKING=1` or set `use_gpu` as `no` in the config to debug on cpu, which helps you in locating the issue.
> 
> Well , this is the traceback information: ![2023-05-24 15-44-14屏幕截图](https://user-images.githubusercontent.com/71422364/240526592-f093b4f6-ab93-4275-8eec-722fa826c97b.png)

Thanks. ALBERT/BERT was used in our experiment. I'll look into this later with RoBERTa model.
